### ISSUE TITLE
train.pyの学習数について

### ISSUE THREAD

**Issue by miyasou714** [Hiroshiba/become-yukarin#10]
学習はtrainerを使用して学習していると思いますが
`trainer = training.Trainer(updater, out=arguments.output)`
こちらではtriggerが指定されていないようです
何iterationで学習を切り上げる、lossがどの程度になったら学習を切り上げるなどの知見はありますか？

**Comment by Hiroshiba** [comment]
デモ動画作成時は、19万イテレーションのものを使いました。

切り上げはスペクトログラムや音声を実際に視聴して適当に決めていました。
また、判別器のaccuracyを見て、テストするアタリを付けていました。
accuracyが0.7程度まで下がった後、0.9まで上がり、その後緩やかに下がっていったと思います。
その推移が変化する辺りのモデルを使って視聴テストしました。
