### ISSUE TITLE
extract_acoustic_feature.pyによる音調特徴量の切り出しで、RuntimeWarningが出る

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#12]
以下のように指定して、実行してみたところ、RuntimeWarnigを吐きます。どうしたらよいでしょうか。パス指定は間違っていないと思います。どうもnumpyのエラーのようですが。
C:\become-yukarin\become-yukarin>python scripts/extract_acoustic_feature.py -i1 \My_ATR503 -i2 \Sasara_ATR503 -o1 \out_MyATR503 -o2 \out_SasaraATR503
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
 (中略)
C:\Users\KHB15\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\KHB15\Anaconda3\lib\site-packages\numpy\core\_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
C:\Users\KHB15\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3194: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)
C:\Users\KHB15\Anaconda3\lib\site-packages\numpy\core\_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
C:\Users\KHB15\Anaconda3\lib\site-packages\numpy\core\_methods.py:125: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)

**Comment by Hiroshiba** [comment]
> Mean of empty slice.
なので、入力ファイルが１つも見つけられていないと思います。
パスがうまく指定できてないと思われます。

https://github.com/Hiroshiba/become-yukarin/blob/210e8225e4f7c95d6d0c89309b5b1eb20e41e744/scripts/extract_acoustic_feature.py#L191
ここの`paths1`をprintしてみて、`[]`（空配列）が表示されたら、指定がうまくできてないことを確認できると思います。
