### ISSUE TITLE
2段階目の学習文数

### ISSUE THREAD

**Issue by miyasou714** [Hiroshiba/become-yukarin#13]
第２段階の学習で
> １つのディレクトリの超大量の結月ゆかり音声データを置く

とありますが、だいたい何文(何時間分)程の学習データを使用されてますか？
結月ゆかりにJNASを読ませたものを使用してる感じでしょうか？

**Comment by Hiroshiba** [comment]
私はJNASを読ませたものを用いました。
pix2pixの元論文の結果を見ると、数十〜数百枚の画像でもそれなりに変換できそうなので、もっと少ない数でも構わないかもしれません。
