### ISSUE TITLE
extract_acoustic_feature.pyによる音響特徴量の切り出しでエラーを吐く

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#14]
PRINTデバッグしてみたところ、path1の指定はうまくいったようです。が、エラーが出ます。このエラーは何でしょうか？

C:\become-yukarin\become-yukarin>python scripts/extract_acoustic_feature.py -i1 My_ATR503 -i2 Sasara_ATR503 -o1 out_MyATR503 -o2 out_SasaraATR503
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
 (中略)
[WindowsPath('My_ATR503/A01.wav'), WindowsPath('My_ATR503/A02.wav'), WindowsPath('My_ATR503/A03.wav'), WindowsPath('My_ATR503/A04.wav'), WindowsPath('My_ATR503/A05.wav'), WindowsPath('My_ATR503/A06.wav'), WindowsPath('My_ATR503/A07.wav'), WindowsPath('My_ATR503/A08.wav'), WindowsPath('My_ATR503/A09.wav'), WindowsPath('My_ATR503/A10.wav'), WindowsPath('My_ATR503/A11.wav'), WindowsPath('My_ATR503/A12.wav'), WindowsPath('My_ATR503/A13.wav')]
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\KHB15\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\KHB15\Anaconda3\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\become-yukarin\become-yukarin\scripts\extract_acoustic_feature.py", line 91, in generate_feature
    f1 = acoustic_feature_process1(wave1, test=True).astype_only_float(numpy.float32)
  File "C:\become-yukarin\become-yukarin\become_yukarin\dataset\dataset.py", line 130, in __call__
    f0 = pyworld.stonemask(x, _f0, t, fs)
AttributeError: module 'pyworld' has no attribute 'stonemask'
"""
(中略)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/extract_acoustic_feature.py", line 209, in <module>
    main()
  File "scripts/extract_acoustic_feature.py", line 202, in main
    pool.starmap(generate_feature, zip(paths1, paths2), chunksize=16)
  File "C:\Users\KHB15\Anaconda3\lib\multiprocessing\pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\KHB15\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
AttributeError: module 'pyworld' has no attribute 'stonemask'

**Comment by Hiroshiba** [comment]
すみません、わかりません。
`pyworld`のリポジトリで聞くと有用な回答が得られるかもしれません。
https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder
