### ISSUE TITLE
WORLDのpythonラッパーについて

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#19]
https://github.com/yamachu/WORLD4pyとhttps://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoderのどちらを使っているのでしょうか？

**Comment by Hiroshiba** [comment]
どちらも使っています。

というのも、後者のライブラリを用いて開発していたのですが、
特定の環境で後者が動かない現象が発生したため、そこだけ前者のライブラリを用いたためです。

まとまった時間が取れたときに、片方に寄せたいです。
