### ISSUE TITLE
 AttributeErrorが出やすい原因

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#20]
Python でモジュール利用時に AttributeError が出た時はファイル名ディレクトリ名が被ってないか調べること
http://d.hatena.ne.jp/shouh/20160105/1451997517
教訓: モジュール名と同名のディレクトリ名orファイル名にするな。これ守られてるんでしょうか？

**Comment by Hiroshiba** [comment]
守られていません。
