### ISSUE TITLE
train.pyによる学習

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#24]
以下のエラーが出ます。

 train.py
C:\Users\KHB15\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\become-yukarin\become-yukarin\train.py", line 19, in <module>
    parser = argparse.ArgumentParser()
NameError: name 'argparse' is not defined

**Comment by BURI55** [comment]
pip install h5py==2.8.0rc1でh5pyのエラーは収まりましたが、NameError: name 'argparse' is not definedが引き続き出ます。

**Comment by BURI55** [comment]
import argparseを冒頭に追加しました。train.py: error: the following arguments are required: config_json_path, outputが出ます。

**Comment by Hiroshiba** [comment]
`train.py`にはもともと`import argparse`が追加されているはずです。
https://github.com/Hiroshiba/become-yukarin/blob/210e8225e4f7c95d6d0c89309b5b1eb20e41e744/train.py#L1

今一度コードをお確かめ下さい。
