### ISSUE TITLE
動作推奨環境について

### ISSUE THREAD

**Issue by hkitahara** [Hiroshiba/become-yukarin#27]
素晴らしい研究をありがとうございます。背景にいたく共感しました。

推奨環境はUnix系のpython3.6以上でしょうか。その他環境ではエラーが発生します。
・Windows環境ではマルチスレッド処理のpickleでエラーが起きます
・Unix環境であってもpython3.5以下だと型宣言でエラーが起きます(PEP-526は3.6以降のみ) 
(READMEに記載しておくとサポート対応が減るかと思います)

**Comment by Hiroshiba** [comment]
ご連絡ありがとうございます。
私はUnix系のpython3.6.3で学習させていました。READMEに記載しておきます。
