### ISSUE TITLE
GPUについて

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#29]
GPUは必要ですか？
どれぐらいのスペックが必要ですか？

**Comment by Hiroshiba** [comment]
GPUは無くても動きますが、とても遅くなるはずです。
特徴量変換の学習はTitanXで数時間かかりました。
高音質化の学習はTitanXで３日ほどかかりました。
また、CPUだと実利用時にリアルタイム変換が間に合いませんでした。
（１秒の音声を変換するのに１秒以上かかってしまう）

私は実利用時にGTX1060を用いています。これならリアルタイム変換が間に合いました。
