### ISSUE TITLE
NumpyのRuntime Errorで困っています。

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#3]
前提・実現したいこと
Phythonでbecome-yukarinを動かそうとしています。
Readme.mdに従い、Githubクローン、Python3.6(Anaconda)インストール、環境整備を行い、
音響特徴量の切り出しを行おうと、scripts/extract_acoustic_feature.pyを4つパスの引数付けて実行してみましたが、エラーが出ます。

発生している問題・エラーメッセージ

> 

C:\become-yukarin\become-yukarin>python scripts/extract_acoustic_feature.py -i1 \My_ATR503 -i2 \Sasara_ATR503  -o1 \out_MyATR503 -o2 \out_SasaraATR503
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_args',
 '_get_kwargs',
 'alpha',
 'disable_alignment',
 'enable_overwrite',
 'f0_ceil1',
 'f0_ceil2',
 'f0_estimating_method',
 'f0_floor1',
 'f0_floor2',
 'frame_period',
 'ignore_feature',
 'input1_directory',
 'input2_directory',
 'order',
 'output1_directory',
 'output2_directory',
 'pad_second',
 'pre_converter1_config',
 'pre_converter1_model',
 'sample_rate',
 'top_db']
C:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Anaconda3\lib\site-packages\numpy\core\_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
C:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3194: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)
C:\Anaconda3\lib\site-packages\numpy\core\_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
C:\Anaconda3\lib\site-packages\numpy\core\_methods.py:125: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)

該当のソースコード

``
C:\become-yukarin\become-yukarin>python scripts/extract_acoustic_feature.py -i1 \My_ATR503 -i2 \Sasara_ATR503  -o1 \out_MyATR503 -o2 \out_SasaraATR503
``
試したこと
extract_acoustic_feature.pyに引数で学習データの入力出力を指定した。
193行lobになっていたのでglobに修正
引数を4つにした。

補足情報（FW/ツールのバージョンなど）
Python3.6(Anaconda)

 ファイル構造 My_ATR503とSasara_ATR503を追加しました。
```
``
├── become_yukarin  # このディレクトリは外から使えることを想定
│  ├── init.py
│  ├── config.py  # 学習の設定パラメータ
│  ├── data_struct.py  # データ構造の定義
│  ├── dataset
│  │  ├── init.py
│  │  ├── dataset.py  # データ処理
│  │  └── utility.py
│  ├── model.py  # ニューラルネットワーク構造
│  ├── param.py  # 音声パラメータ
│  ├── updater.py  # chainerのUpdater
│  └── voice_changer.py  # 学習済みモデルを使って声質変換
├── recipe
│  ├── config.json  # 学習の設定パラメータ
│  └── recipe.json  # 複数の学習を回す時のパラメータ
├── requirements.txt  # 依存関係のあるライブラリ
├── scripts
│  ├── extract_acoustic_feature.py  # 音響特徴量切り出し
│  ├── launch.py  # 複数の学習を回す
│  ├── ln_apply_subset.py
│  ├── ln_atr503_to_subset.py
│  ├── ln_jnas_subset.py
├── tests
│  ├── init.py
│  └── test_dataset.py
└── train.py  # 学習用のスクリプト  └── voice_changer.py  # 学習済みモデルを使って声質変換
├── recipe
│  ├── config.json  # 学習の設定パラメータ
│  └── recipe.json  # 複数の学習を回す時のパラメータ
├── requirements.txt  # 依存関係のあるライブラリ
├── scripts
│  ├── extract_acoustic_feature.py  # 音響特徴量切り出し
│  ├── launch.py  # 複数の学習を回す
│  ├── ln_apply_subset.py
│  ├── ln_atr503_to_subset.py
│  ├── ln_jnas_subset.py
├── tests
│  ├── init.py
│  └── test_dataset.py
└── train.py  # 学習用のスクリプト
``

**Comment by Hiroshiba** [comment]
スクリプトの引数は、glob形式が入ることを想定しています。
`./My_ATR503`はディレクトリなので、`./My_ATR503/*.wav`みたいな形で指定すれば、変わるかもしれません。
