### ISSUE TITLE
1段目学習時のdiscriminator/accuracy

### ISSUE THREAD

**Issue by miyasou714** [Hiroshiba/become-yukarin#31]
1段目の学習についてなのですが
discriminator/accuracyの推移を見ると
以前こちらのissue https://github.com/Hiroshiba/become-yukarin/issues/10 で回答されていたような挙動とは異なった推移をしています
GANのaccuracyとしては上下しながら減少していくのが自然かと考えたのですが…
いくつかモデルの学習を行った際にaccuracyの推移の傾向が毎回異なるなどはありましたか？
(学習データはATR503文中のサブセットjを除いた450文を使用しております)
![tda](https://user-images.githubusercontent.com/25506318/38405272-09f9a49e-39aa-11e8-99c0-005c303e1634.png)

predictor/lossも図示してみたのですが
250*250iteration付近から上昇しているのが気になります
これはpredictorの学習に失敗しているということでしょうか？
![ploss](https://user-images.githubusercontent.com/25506318/38407656-52479cfa-39b5-11e8-8bdc-70626fd502e2.png)

**Comment by Hiroshiba** [comment]
> いくつかモデルの学習を行った際にaccuracyの推移の傾向が毎回異なるなどはありましたか？
多少異なることはありましたが、大まかな形は似たり寄ったりでした。

> これはpredictorの学習に失敗しているということでしょうか？
なんとも言えませんが、余りいい感じに学習できていない気がします。
こうなる理由としては、例えばDiscriminatorが強すぎる、もしくは過学習しているなどが考えられます。

まず最初にですが、predictorが悪いのか、GAN（discriminator）が悪いのかを切り分けると良いように感じます。
（config.jsonのlossのadversarialを0にすれば、discriminatorを無視して学習することが出来ます。）

これは私の経験なのですが、Discriminatorのaccuracyが1に張り付くと、良い音声変換になりません。
predictorがそれなりにうまく学習できたら、次は、Discriminatorが強すぎるのをなんとかすると良いと思います。
