### ISSUE TITLE
train.py実行エラーについて

### ISSUE THREAD

**Issue by prey28** [Hiroshiba/become-yukarin#33]
実行環境：windows10 anaconda

src,yukariに録音音声,ゆかり音声を入れ

python scritpts/extract_acoustic_feature.py -i1 src -i2 yukari -o1 src2 -o2 yukari2

を実行し、src2,yukari2に*.npyとmean.npy,var.npy出力できました。
次に、recipe/config.jsonのinput_glob,input_mean_path,input_var_pathをsrc2のファイルを設定
target_glob,target_mean_path,target_var_pathをyukari2のファイルを設定

python train.py recipe/config.json result

  File "C:\yukari\become-yukarin-master\become_yukarin\dataset\dataset.py", line 272, in __call__
    f0[~data.voiced] = 0
TypeError: bad operand type for unary ~: 'float'

と、エラーが出てしましました。

data.voiced=>"nan"
となっており、jsonファイルの設定間違いか、コマンドライン引数の間違いでしょうか。

**Comment by prey28** [comment]
反応ありがとうございます。

上記のエラーですが、自己解決しました。
原因はinput_glob,target_globにmean,varのファイルも含まれていたためでした。

ただ、それを解決しても

 File "C:\yukari\become-yukarin-master\become_yukarin\dataset\dataset.py", line
 493, in <lambda>
    return LambdaProcess(lambda d, test: dict(seed=numpy.random.randint(2 ** 32), **d))
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32

と新しいエラーが出てしまいました。

推奨環境のUnix系環境を構築してみます。

**Comment by Hiroshiba** [comment]
> 原因はinput_glob,target_globにmean,varのファイルも含まれていたためでした。
なるほどです。

> ValueError: high is out of bounds for int32
当てずっぽうですが、`2 ** 32`の部分を、`2 ** 10`とかに小さくすれば動く気がします。

Issueは一旦閉じます。
また進展があればここをOpenして頂くか、別のIssueを建ててください。
