### ISSUE TITLE
音響特徴量切り出しがうまくいかない

### ISSUE THREAD

**Issue by KAZUHA0604** [Hiroshiba/become-yukarin#37]
\become-yukarin-master\scripts> python extract_acoustic_feature.pyTraceb
ack (most recent call last):
  File "extract_acoustic_feature.py", line 12, in <module>
    from become_yukarin.acoustic_converter import AcousticConverter
ModuleNotFoundError: No module named 'become_yukarin'
といったエラーをだします。

上記の問題は解決しましたが、次は最後のnamed 'world4py'になりました

**Comment by Hiroshiba** [comment]
WORLD4pyをインストールする必要があります。
https://github.com/yamachu/WORLD4py

この辺りの依存関係をまとめてわかりやすくする準備中です。
