### ISSUE TITLE
extract_acoustic_feature.py実行時のSyntaxError

### ISSUE THREAD

**Issue by KinoPSoft** [Hiroshiba/become-yukarin#41]
【実行環境】
Ubuntu17.10
Nvidia Toolkit 9.2
cuDNN7.2.1

チップの種類：NVIDIA GeForce GT 730
利用可能な全グラフィックスメモリ：4096MB
requirements.txtにあるライブラリは全てインストールしました

【コマンド】
`PYTHONPATH='pwd' python scripts/extract_acoustic_feature.py ---`

【エラー文】
`File "scripts/extract_acoustic_feature.py", line 137
    def generate_mean_var(path_directory: Path):
                                        ^
SyntaxError: invalid syntax`

【参考】
https://qiita.com/atticatticattic/items/f1e4c671d73d815bbad2  を参考に進めて、「6.2 音響特徴量切り出しをする」の「`python scripts/extract_acoustic_feature.py -i1 dat/in_1st_my_wav -i2 dat/in_1st_yukari_wav -o1 dat/out_1st_my_npy  -o2 dat/out_1st_yukari_npy`」を実行した場合にも上記と同様のエラーが出てしまいます。

解決策などありましたらどうかご教授ください。
よろしくお願いします。

**Comment by Hiroshiba** [comment]
Invalid Syntaxは構文エラーです。
おそらくですが、pythonのバージョンが低いと思われます。python3.6以上を用いると解決できるかもしれません。

エラー箇所の
`def generate_mean_var(path_directory: Path):`
の`: Path`は、比較的新しいpythonの記法なため、そう推測しました。

一度issueは閉じますが、上記の方法で解決できなければissueをopenにして再度お聞きください。
