### ISSUE TITLE
モデルの余剰部分について

### ISSUE THREAD

**Issue by toda-necgene** [Hiroshiba/become-yukarin#42]
トーダと申します。いつも生放送を拝見しております。
SRおよび変換モデルについてなのですが、ソースコードを読む限りではConv-BatchNorm(BN)-Relu構造を使用していると見受けられるのですが、Convolutionレイヤーでnobias=Falseとなっています。BNでは平均を0分散を1に正規化しています。そのためこの構造ではbiasを使用する意味はないと思われます。重箱の隅をつつくようで申し訳ないのですが、高速化の観点から削減すべきだと思っております。
長文失礼いたしました。

**Comment by Hiroshiba** [comment]
おっしゃる通りです。気が向いた時に修正したいと思います。
