### ISSUE TITLE
scripts/super_resolution_test.pyを実行した際にerror!が出る

### ISSUE THREAD

**Issue by KinoPSoft** [Hiroshiba/become-yukarin#43]
環境：ubuntu17.10.1

【実行したコード】
PYTHONPATH=`pwd` python scripts/super_resolution_test.py yukari_2nd -md dat/model -iwd dat/in_2nd_yukari_many_wav

【結果】
dat/model/yukari_2nd/predictor_24300.npz

error! test_data_sr/音声.wav

音声の周波数を統一していないのが要因だと思われますが、他に考えられる要因はございますでしょうか。
もしあればご教示ください。
よろしくお願いします。

**Comment by Hiroshiba** [comment]
難しいですが、例えば音声が短すぎたりしてもエラーが出るかもしれません。

issueは一度閉じますが、続きで聞きたいこと等あれば再度openしてください。
