### ISSUE TITLE
Can you please host the pre-trained networks?

### ISSUE THREAD

**Issue by Em-Lopez** [Hiroshiba/become-yukarin#44]
I do not have a GPU.
Training the network will take a long time, because I do not have a GPU.
I just want to be a cute girl.
Can you please upload the pretrained network weights?

**Comment by Hiroshiba** [comment]
Sorry, I don't think upload the pretrained model.
Because I used the dataset made from the VOICEROID product.

We can use Google Colaboratory that is the system usable GPU.
You can do it!
