### ISSUE TITLE
Is there way to resume the training?

### ISSUE THREAD

**Issue by chikiuso** [Hiroshiba/become-yukarin#46]
Hi, is there way I could stop and resume the training? Not start the training from first iteration? Thanks!

**Comment by Hiroshiba** [comment]
There is no method for additional training.
But you can implement with chainer code.

For example, after making model (at https://github.com/Hiroshiba/become-yukarin/blob/7fe29af7a15dddcf8220733472cb985019aa1e87/train.py#L30 ), please load trained model.
