### ISSUE TITLE
ステレオ入力・ステレオ出力

### ISSUE THREAD

**Issue by Raihuku** [Hiroshiba/become-yukarin#47]
初めまして
質問お願い致します。

学習用の音声データにステレオの音源を使用しても
モノラル化して(?)学習し、モノラルで出力されるようになっているようですが

変換結果もステレオにすることはできますでしょうか？

**Comment by quillkiragimmy** [comment]
Actually the binaural (stereo) voice can be reconstructed by:
1. difference of amplitude between L/R.
2. difference of phase between L/R.
Basically what you need can be achieved by start one channel 50ms latter than the other, that will make it sounds like stereo, and some reverb might help as well.

**Comment by Hiroshiba** [comment]
モノラル化して学習・変換するようになっています。
現状だと、ステレオ音源のL/Rそれぞれをモノラル音源として２つファイルを書き出したあと、各々で変換し、後にステレオとして結合するなどの方法などがありそうです。
