### ISSUE TITLE
WAVに変換できません

### ISSUE THREAD

**Issue by usasho** [Hiroshiba/become-yukarin#50]
ヒホさんのリポジトリーも同じエラーが出ています
voice_conversion_test.pyを実行したのですが　エラーが出ます
音声データは　16Bit　16000Hz　１Ch　約20秒　なのですが
Linux Ubuntu Base  Feren OS 
Python3.6 4GB Core i3  Swap 2Gb No GPU

error! dat/out_1st_my_npy/1.npy
Traceback (most recent call last):
  File "scripts/voice_conversion_test.py", line 39, in process
    fn = glob.glob(str(input_wave_directory / p.stem) + '.*')[0]
IndexError: list index out of range

**Comment by Hiroshiba** [comment]
そのファイルでは、学習に使ったときの入力wavファイルを声質変換しています。
おそらく、学習に使ったwavファイルが見つからないため、エラーが出ています。

試しに学習済みモデルで声質変換したいのであれば、
test_dataディレクトリに音声を配置する手もあります。
ここのコードが参考になると思います。
https://github.com/Hiroshiba/become-yukarin/blob/7fe29af7a15dddcf8220733472cb985019aa1e87/scripts/voice_conversion_test.py#L28

issueは一度閉じますが、また問題があればopenしてください。
