### ISSUE TITLE
パラメータの意味について

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#53]
第一段階第二段階のの学習でモデルのログファイルに出力されるiterationの意味(5000ごとにファイルを吐き出すようになっているようだ。)と、第二段階の学習がGPUメモリが少なくて動かない時にdatフォルダのconfig_sr.jsonで下げて設定するbatchsizeやtrain_crop_sizeやgenerator_base_channelsの意味を教えてください。ちなみにGTX10603GBではヒホさんの設定では動かなくて、batchsizeを2から1、train_crop_sizeを512から256、generator_base_channesを64から32にして第二段階の学習を回しています。これによって精度が落ちることは考えられるでしょうか？またGPUメモリがたくさんあるGPUで、この数値を上げると精度が増すということは考えられるでしょうか？

**Comment by Hiroshiba** [comment]
iterationやbatchsizeは機械学習の基礎なため、説明を省きます。

train_crop_sizeは過去のissueを見てください。
generator_base_channelsはCNNのチャンネル数と比例していて、大きいほどチャンネル数が増えます。

精度については試していないのでわかりません。
直感的には、それらの値でもそこまで大きく精度が下がることは無いと思います。

もし追加でわかったことがあったら、ぜひ共有してください。

**Comment by BURI55** [comment]
train_crop_sizeの意味 #35
