### ISSUE TITLE
AttributeError: Can't pickle local object 'create_sr.<locals>.<lambda>'

### ISSUE THREAD

**Issue by yuuSiVo** [Hiroshiba/become-yukarin#54]
AttributeError: Can't pickle local object 'create_sr.<locals>.<lambda>' 

Windows環境でbecome-yukarinのtrain_srを動かそうとした時に、上記のエラーが発生しました。

環境: 
windows10 64bit
Python 3.7
Chainer3.5.0です

**Comment by Hiroshiba** [comment]
Windows環境はわかりません。申し訳ありません。
numpyやchainerのバージョンを上げると解決できるかもしれません。

このissueは閉じますが、何かわかったらぜひこのissueにコメントしてください。

**Comment by BURI55** [comment]
このissue内の動作推奨環境について #27( https://github.com/Hiroshiba/become-yukarin/issues/27)
もご参照ください。
