### ISSUE TITLE
イテレーションについて

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#55]
イテレーションは第一段階、第二段階どれぐらい回しているのでしょうか？
参考までに教えていただきたいです。
ヒホさんの学習はTITANXで第一段階数時間、第二段階三日だそうですが、
1時間10000npzとして、第一段階数万npz、第二段階36万npzぐらいでしょうか？
学習量が多ければ声質変換の精度も上がるのですか？(特に第二段階)

**Comment by Hiroshiba** [comment]
第１段階は多対１声質変換で１００万～３００万イテレーション、
第２段階は３０万イテレーションくらいです。

第１段階、第２段階ともにGANの学習が含まれており、精度は数十万イテレーション程度で上がらなくなります。
