### ISSUE TITLE
収録データのサンプリング周波数について

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#56]
ヒホさんが24kHzを選択した理由は何でしょうか？
映像業界で48KHzが基本だからその半分の周波数という説と
音声研究界で16kHzが基本だったからその1.5倍の周波数という説がありますが、
どうなんでしょうか？
ちなみにゆかりさんはvoiceroid EX+で、21.5kHzで、Voiceroid2で44.1kHzですから、
soxかなんかでvoiceroid2のものをダウンコンバートして用いているのですか？
としたら、その理由は何でしょうか？

**Comment by Hiroshiba** [comment]
4000Hz程度で区切って試してみて、自分の耳で許せる音質になったのが24000Hzだったためです。
