### ISSUE TITLE
script/super_resolution_test.py のexcept のエラー出力

### ISSUE THREAD

**Issue by YoshikazuOota** [Hiroshiba/become-yukarin#58]
ソース修正のご提案があります。

script/super_resolution_test.py L59 の
```traceback.format_exc()```
を
```print(traceback.format_exc())```
とされた方が良いかと思います。
現状では、エラーが表示されないため、エラー原因の特定が難しくなるかと思います。

以上、ご検討いただければ幸いです。

**Comment by Hiroshiba** [comment]
修正しました。ご報告ありがとうございます。
