### ISSUE TITLE
音響特徴量の切り出しのコマンドのエラー

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/become-yukarin#7]
アウトプットには何を指定するといいのですか？
また、ファイル名はA01～A13.wavをを指定していますが、これで良いのですか？

C:\become-yukarin\become-yukarin>python scripts\extract_acoustic_feature.py -i1 ../My_ATR503/*.wav -i2 ../Sasara_ATR503/*.wav -o1 ../out_MyATR503/*.wav -o2 ../out_SasaraATR503/*.wav
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_args',
 '_get_kwargs',
 'alpha',
 'disable_alignment',
 'enable_overwrite',
 'f0_ceil1',
 'f0_ceil2',
 'f0_estimating_method',
 'f0_floor1',
 'f0_floor2',
 'frame_period',
 'ignore_feature',
 'input1_directory',
 'input2_directory',
 'order',
 'output1_directory',
 'output2_directory',
 'pad_second',
 'pre_converter1_config',
 'pre_converter1_model',
 'sample_rate',
 'top_db']
Traceback (most recent call last):
  File "C:\Anaconda3\lib\pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "C:\Anaconda3\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: '..\\out_MyATR503\\*.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts\extract_acoustic_feature.py", line 208, in <module>
    main()
  File "scripts\extract_acoustic_feature.py", line 197, in main
    arguments.output1_directory.mkdir(exist_ok=True)
  File "C:\Anaconda3\lib\pathlib.py", line 1235, in mkdir
    if not exist_ok or not self.is_dir():
  File "C:\Anaconda3\lib\pathlib.py", line 1326, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Anaconda3\lib\pathlib.py", line 1136, in stat
    return self._accessor.stat(self)
  File "C:\Anaconda3\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: '..\\out_MyATR503\\*.wav'

**Comment by BURI55** [comment]
*が抜けていました。どうもパス指定で詰まっているようですね。
C:\become-yukarin\become-yukarin>python scripts\extract_acoustic_feature.py -i1 ../My_ATR503/*.wav -i2 ../Sasara_ATR503/*.wav -o1 ../out_MyATR503/*.wav -o2 ../out_SasaraATR503/*.wav
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_args',
 '_get_kwargs',
 'alpha',
 'disable_alignment',
 'enable_overwrite',
 'f0_ceil1',
 'f0_ceil2',
 'f0_estimating_method',
 'f0_floor1',
 'f0_floor2',
 'frame_period',
 'ignore_feature',
 'input1_directory',
 'input2_directory',
 'order',
 'output1_directory',
 'output2_directory',
 'pad_second',
 'pre_converter1_config',
 'pre_converter1_model',
 'sample_rate',
 'top_db']
Traceback (most recent call last):
  File "C:\Anaconda3\lib\pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "C:\Anaconda3\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: '..\\out_MyATR503\\*.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts\extract_acoustic_feature.py", line 208, in <module>
    main()
  File "scripts\extract_acoustic_feature.py", line 197, in main
    arguments.output1_directory.mkdir(exist_ok=True)
  File "C:\Anaconda3\lib\pathlib.py", line 1235, in mkdir
    if not exist_ok or not self.is_dir():
  File "C:\Anaconda3\lib\pathlib.py", line 1326, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Anaconda3\lib\pathlib.py", line 1136, in stat
    return self._accessor.stat(self)
  File "C:\Anaconda3\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: '..\\out_MyATR503\\*.wav'

**Comment by BURI55** [comment]
アスタリスクが消えてしまいます。

**Comment by Hiroshiba** [comment]
アウトプットには、ディレクトリのパスを指定してください。
アスタリスクが消えるのは、ターミナルかシェルの仕様だと思われます。
たぶん、`'directory/*.npy'`みたいな形で、シングルクォートで囲えば、展開されないと思います。
