### ISSUE TITLE
train.pyでZeroDivisionError: division by zeroのエラーが出る。

### ISSUE THREAD

**Issue by takka-919** [Hiroshiba/become-yukarin#9]
学習第一段階でtrain.pyを実行すると、/chainer/iterators/multiprocess_iterator.pyで
`previous_epoch_detail = epoch + pos / n  ZeroDivisionError: division by zero`というエラーになる問題で困っています。
原因または解決策をご存知の方はいらっしゃいませんか。

`PYTHONPATH='pwd' python train.py recipe/config.json output`

を実行すると、以下のような結果になりました。

> /home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
>   from ._conv import register_converters as _register_converters
> Exception in main training loop: division by zero
> Traceback (most recent call last):
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
>     update()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
>     self.update_core()
>   File "/home/lab/jupyterhome/takakura/workspace/become-yukarin/become_yukarin/updater/updater.py", line 82, in update_core
>     batch = self.get_iterator('main').next()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 86, in __next__
>     batch, prefetch_state = self._prefetch_loop.measure()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 286, in measure
>     indices = self._proceed()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 361, in _proceed
>     previous_epoch_detail = epoch + pos / n
> Will finalize trainer extensions and updater before reraising the exception.
> Traceback (most recent call last):
>   File "train.py", line 83, in <module>
>     trainer.run()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/training/trainer.py", line 313, in run
>     six.reraise(*sys.exc_info())
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
>     update()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
>     self.update_core()
>   File "/home/lab/workspace/become-yukarin/become_yukarin/updater/updater.py", line 82, in update_core
>     batch = self.get_iterator('main').next()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 86, in __next__
>     batch, prefetch_state = self._prefetch_loop.measure()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 286, in measure
>     indices = self._proceed()
>   File "/home/lab/anaconda2/envs/dl/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 361, in _proceed
>     previous_epoch_detail = epoch + pos / n
> ZeroDivisionError: division by zero
> 

原因として考えられるのが入力、出力音声の条件かと考えているのですが、
なにかこれらに条件はありますか？

なお、私の環境は以下の通りです。
【MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports), メモリ量 16 GB 2133 MHz LPDDR3, , OSX 10.13.3, python3.6】

不足情報等あればお申し付けください。
宜しくお願いいたします。

**Comment by Hiroshiba** [comment]
chainerの`multiprocess_iterator.py`の`previous_epoch_detail = epoch + pos / n`のnは、データセット数です。
https://github.com/chainer/chainer/blob/3a44f3737d2dd379cdcb919e6c8ce2a47347d73d/chainer/iterators/multiprocess_iterator.py#L369
そこが`ZeroDivisionError`になるということは、データセット数が０になっています。

`config.json`で指定する入力データや出力データのファイルパスを間違えていたりすると、ファイルを探せずにデータ数が０になります。
このあたりが原因かもしれません。

（いったんこちらのissueは閉じますが、何かあればコメントしてください。）

**Comment by takka-919** [comment]
ファイルパスを間違えた場合は違うエラーが出て来ました。

おそらく、音響特徴量抽出の際、npyファイルの生成がうまくいっていないのかと思うのですが
scripts/extract_acoustic_feature.pyの入出力ファイルには何か条件がありますでしょうか？（同じ長さの音源でなければならないなど）

**Comment by Hiroshiba** [comment]
waveファイル数だけ合わせれば動くように作ったので、特に条件は無いはずです。

**Comment by batorrrgil** [comment]
ゼロ除算エラーで同じ問題があります。
ファイル名を何度も確認しました。
助けて

**Comment by YoshikazuOota** [comment]
うろ覚えですが、npyファイルの生成に問題があったときに、同様のエラーが発生した記憶があります。
自分の場合は、npyファイルを全削除して生成し直したらなおりました。

■ ご確認事項
npyファイルのサイズが0になっていないか確認してみてください。
もし、サイズが 0になっているものがあれば、npyファイルの生成に失敗していると思われます。

■ npyファイルの生成に失敗するケース(経験則)
・npyファイル生成プログラムが中断した場合
・音声ファイルが極端に短い場合

もしよろしければ、DiscordのYukarinライブラリの同好会にいらしてください。
お手伝いできるかもしれません。
https://discord.gg/eR3sU2v
